language: node_js
node_js:
  - '6'
deploy:
  provider: npm
  email: sam@samnoedel.com
  api_key:
    secure: l9lj+9b4cdg8LFtf+HlvLuby0Y0xH1nGLTdXz7gChF3TExb6TYopXDfsk+LtljvJQ8NIiiKHKlel9NOzygP0FscRtdU9rkUj7x07T1OX3Mlz9zg0tIJD0MKc1X1G8y+ZRRzhK4RQNcWotuL92x46LgVng3fIUXInOzg8euBjsAJBOV9cEMF42I8q4sHa8vGN7zx9YFwZbnRZRjfvSpcVXQ8pxGnQmP3x5sOj3RMPT2FKOTqegnCddshyLBIyv7i1hTNPLzSE8qL342LhaWPs1MOGi78cOwQNqOi5W/Ap6d5PWoUFzBONPeCNYLoEYnJEtcgukwJvxfsPKlygyu4M1mBSVmeQC+r7Q74/JZ/ua1x4h+Y9QCHJ3r1if1KPAh5qi8C3DYzvyb+b0WWYxQh+eOq+a8I2FkfEKz9CaWmlqUBwCFewV1AvHBIcaDLKLOht0Y6R5LNeLq8Zd5dqsVSLo5DWZlFSQveV6RdVbat7DtzcJihj5nob4LHXGLDf7/tvZ0N3/rzddXi/nRNQN4TWzJ5nyyNFq7DBbG17UBo5zua2hiu/czH6xWBFV5UAPzym6tr7eDMJhvY5apnLlDK6Ertx2tQQ+TIK2r3DmlH8lrsMoJD2tVpSDh3/Vts3RLN4VkacRLsrEHTbO4vfiGTZ4OcA5onp1zmjtg7V6huAkfQ=
  on:
    tags: true
    repo: rune-catalog/rune-ui-resources
